### ISSUE TITLE
如何删除啊。安装后

### ISSUE THREAD

**Issue by phonehold** [huhamhire/huhamhire-hosts#12]
如何删除。我mac安装后，想删除怎么删除？用的dmg的。。
还有我改本机hosts已经不生效了。。。
为什么只有安装文档，没有卸载呢

**Comment by huhamhire** [comment]
在root权限下，使用任意编辑器修改/etc/hosts文件，将其内容替换成以下条目即可：
127.0.0.1   localhost
255.255.255.255   broadcasthost
::1         localhost 
fe80::1%lo0   localhost

**Comment by phonehold** [comment]
。。我知道在这里改。。不过最大的问题不在这里。。。。。真悲剧啊。。 我把你程序备份的配置重新弄到/etc/hosts下面都不成。。然后我删除/etc/hosts。接着再新建一个hosts 就神奇的成功了。。。。
不应是编码的问题吧。。。

**Comment by huhamhire** [comment]
在今年年初的项目整合的时候的确出现了一些编码问题，不过后来应该都解决了~~您后来自己建的hosts文件是空文件吗？

**Comment by phonehold** [comment]
是的。把之前的hosts删除。再vim 新建一个，再接着写127.0.0.1 www.a.com 就可以了。。

**Comment by huhamhire** [comment]
如果是这样的话，未必是编码问题~您有看过原先hosts文件的编码及换行符没？

**Comment by phonehold** [comment]
我之前的一直在用。没有问题。安装后，再改就不生效了。。。。

**Comment by huhamhire** [comment]
那使用的是有线网还是无线网呢？最近我发现Mountain Lion在有线网的环境下可能会优先访问DNS而不是hosts文件的问题，原因暂时木有查明

**Comment by huhamhire** [comment]
还有个办法是使用我们提供的utf8格式的纯hosts文件直接替换，其实用CLI的话要比图形界面方便不少

**Comment by phonehold** [comment]
无线哦。最新的系统。10.8.3  我刚开始用的就是命令行的，我一看有dmg 的心想就下来试试，结果遇到这个情况。不过好再知道问题了，非常感谢。
