### ISSUE TITLE
测试结果

### ISSUE THREAD

**Issue by ghost** [huhamhire/huhamhire-hosts#15]
我在北京通州，我的测试结果：1.如果谷歌web服务和应用程序服务都选择美国服务器，google+能正常打开,但是，不能打开google搜索后的网页，比如，我在谷歌搜索“goagent”,ok,能打开，但是，进而点击goagent的相关网址，无法加载;2.为了能够正常使用google搜素功能，我只能用北京的谷歌web服务，但是，无论google应用程序选择北京服务器还是美国服务器，google+打不开。看来，google和google+不能兼得.

**Comment by huhamhire** [comment]
建议可以先暂时通过手动修改的方式指定 plus.google.com 的地址到美国的服务器，后续待国内服务迁移稳定之后我会发布一次更新
