### ISSUE TITLE
建议加入命令行工具

### ISSUE THREAD

**Issue by hanwentao** [huhamhire/huhamhire-hosts#16]

**Comment by huhamhire** [comment]
下一个版本的将会提供，Curses 界面配置工具，支持简单的非图形界面操作

**Comment by huhamhire** [comment]
1.9.8版本已经发布，有关字符界面的说明可以查阅开发文档中的相关部分 :-)
https://hosts.huhamhire.com/document/intro.html#text-based-user-interface-tui-mode
