### ISSUE TITLE
Google Groups is 403 Error

### ISSUE THREAD

**Issue by johndeng** [huhamhire/huhamhire-hosts#17]
广州电信这边，一修改Hosts就403，删除了就能上。。

**Comment by huhamhire** [comment]
已更新 1.4.4 版本数据包，期待测试反馈 :-P

**Comment by johndeng** [comment]
Hi, 我更新了，Gtalk 一直在loading.

**Comment by huhamhire** [comment]
我用 ThunderBird 可以上 Google Talk，可能还是有部分地址不可靠，我再研究下

**Comment by johndeng** [comment]
OK.

辛苦了。
