### ISSUE TITLE
连接被重置

### ISSUE THREAD

**Issue by ghost** [huhamhire/huhamhire-hosts#18]
我查了一下/etc/hosts文件,里面google的ip 173.x.x.x是google-us那部分的吧?在我这边,第一次能够打开google的网页,可是,进一步加载谷歌搜索后的网页,却是不行: 连接被重置. 我希望还是能够在hosts文件中,区分google-cn和google-us ;-)

**Comment by ghost** [comment]
我用的是最新的1.4.4

**Comment by huhamhire** [comment]
1. 关于连接被重置的问题，你使用的是 google.com 还是 google.com.hk 呢？建议大陆地区用 hk 的域名访问，并且最好能强制开启 https，单纯用 http 存在被重置链接的可能。
2. 关于 hosts 的问题，1.4.4 中的 hosts 文件中的 IPv4 部分已经实现了自动化获取，并依据链接质量及 HTTP 请求情况排序筛选生成最终 hosts 条目，每个域名尽量进行选优并在 hosts 中提供了冗余条目，不再适用原有的按国家地区选择的方式。
3. 关于服务器选择的问题，Google 去年底就开始对东亚服务器进行调整，当前北京的服务器仅保留搜索及翻译功能，香港服务器上提供的内容也会在今年大量迁出，如果继续大量保留先前的 google 北京服务器地址，必然会出现大量 Google 服务无法使用的情况。后续的重点应该会放在筛选算法质量的改进上面 :-P
4. 另外，目前用于在用户端自动化优化生成 hosts 的工具正在开发中，也许以后可以通过在用户端进行链接质量检测，有针对性的提升用户的访问质量 :-)

BTW, 173 开头的未必就是美国服务器，这一段地址应该都是 Google 的，可能会被分配在世界各地的服务器上~~

**Comment by ghost** [comment]
1.受教了. 我非计算机专业出身，对这个领域涉足不深，如果有什么东西说错了，欢迎及时纠正 ;-) 
2.将firefox、chromium、和opera默认强制使用https，果然好多了.
3.google调整服务器，是government逼迫的，还是google自己的意思？
4.祝福huhamhire hosts做的越来越好. ;-)

**Comment by huhamhire** [comment]
从目前的消息来来看，服务器的调整应该是 Google 自己的决定，这个是硬伤 T_T~~

感谢你的支持 :-P
