### ISSUE TITLE
建议屏蔽地址用 0.0.0.0 这样的地址

### ISSUE THREAD

**Issue by achun** [huhamhire/huhamhire-hosts#21]
127.0.0.1 对很多开发者来说不太合适啊.

**Comment by huhamhire** [comment]
0.0.0.0 由于代表整个网络，并不合适。因为地址不可达，可能会导致屏蔽部分的内容在网页加载时存在假死状态。可以考虑改用本地回环的其他地址。

不过基于 hosts 的广告屏蔽效率并不高，建议直接用浏览器插件。后续我也在考虑要逐步去除广告屏蔽功能，仅保留部分软件激活服务器的屏蔽部分，不影响网页体验。

**Comment by achun** [comment]
额, 看来我的基础没有学好啊.
那用 127.0.0.255 这样的好了.

**Comment by huhamhire** [comment]
但是如果你本地有侦听 80 端口的 Web Server 的话，可能会出现与 127.0.0.1 下一样的情况，意义不大。最好的办法还是使用 ABP 这样的插件实现屏蔽。非网页应用的话，应该不会有啥问题。

**Comment by achun** [comment]
开发者要是绑定 ":80" 的话确实是这样. 不过还有常见的 "127.0.0.1:80" 的写法.
不过话说回来,既然是开发者, 改配置到 其他一个127.0.0.x 也很简单.
看来没必要改这个了.
最后开个玩笑:
用 127.0.0.250 吧
