### ISSUE TITLE
youtube video playback

### ISSUE THREAD

**Issue by skela** [huhamhire/huhamhire-hosts#23]
youtube.com works fine, is accessible, but none of the videos that I've tried work. I press play and the youtube indicator spins forever. After a long time an error is shown.
![1](https://cloud.githubusercontent.com/assets/58268/2773168/a37b4ef6-ca91-11e3-97c9-df397c26bbfa.png)
![2](https://cloud.githubusercontent.com/assets/58268/2773169/a37cd096-ca91-11e3-80ee-dd7e5a703fce.png)

Is there anything else I need to do to allow youtube video playback when in China using these hosts?

**Comment by huhamhire** [comment]
@skela 

Since hosts file could only solve the problem caused by DNS spoofing, I'm sorry to say that you cannot watch the videos from Youtube with these hosts currently.

It is highly recommended to use proxy servers and VPN if you need to play the videos. :-)

**Comment by skela** [comment]
Ok thanks, thats what I thought, just wanted to make sure. Keep up the good work, at least I can access google plus and google :D
