### ISSUE TITLE
Error as described.

### ISSUE THREAD

**Issue by ghost** [huhamhire/huhamhire-hosts#27]
richard@gentoo ~/Downloads/kk/HostsTool-x11-gpl-1.9.8-SE $ sudo python2 hoststool.py 
Fontconfig warning: "/etc/fonts/conf.d/44-wqy-zenhei.conf", line 11: Having multiple values in <test> isn't supported and may not work as expected
libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
Traceback (most recent call last):
  File "/home/richard/Downloads/kk/HostsTool-x11-gpl-1.9.8-SE/gui/_make.py", line 103, in run
    self.make()
  File "/home/richard/Downloads/kk/HostsTool-x11-gpl-1.9.8-SE/util/makehosts.py", line 93, in make
    self.get_hosts(self.make_cfg)
  File "/home/richard/Downloads/kk/HostsTool-x11-gpl-1.9.8-SE/gui/_make.py", line 123, in get_hosts
    if not RetrieveData.chk_mutex(part_id, mod_cfg):
  File "/home/richard/Downloads/kk/HostsTool-x11-gpl-1.9.8-SE/util/retrievedata.py", line 283, in chk_mutex
    mutex_info.extend(cls.get_ids(mutex_tuple[mod_id]))
KeyError: 1

Please ignore font issue and libpng warning, Just see traceback.  At this time, Hosts Setup Utility hangs on. see attachment.
![2014-06-14-110615_1366x768_scrot](https://cloud.githubusercontent.com/assets/7656607/3277409/6fad269a-f371-11e3-906c-8606653d878c.png)

**Comment by huhamhire** [comment]
Seems to be a bug

**Comment by ghost** [comment]
Please fix it as soon as possible. Because some service in 1.4.6 doesn't work in Beijing, 1.4.7 may fix these.

**Comment by huhamhire** [comment]
This problem is caused by the incorrect configuration while generating the hosts data file of version 1.4.7. And the adblock list might be unavailable, you can try not using adblock currently. :-)

Since the adblock list would be totally removed from the data file, this problem would not happen in the next version.

**Comment by ghost** [comment]
Your way rocks, thank you. :)

**Comment by ghost** [comment]
This issue has been fixed in 1.4.8, so I decide to close it.
