### ISSUE TITLE
Twitter

### ISSUE THREAD

**Issue by robertpb** [huhamhire/huhamhire-hosts#31]
I still can't get access to twitter. Instead, I get a message saying that the server did not respond. I am using Firefox 30.0. Can anyone tell me why this is going on?

**Comment by huhamhire** [comment]
I'm sorry to say that all IPv4 addresses of twitter's servers has been blocked by Chinese government since 2 years ago, and you can not access twitter services by only modifying the hosts file currently.

**Comment by robertpb** [comment]
Too bad. I wonder why aren't the facebook IPs blocked. :)

**Comment by skela** [comment]
ah, always did wonder why twitter wouldn't work, but facebook had no problems. twitter really pissed of China :D

**Comment by robertpb** [comment]
Now that I know why this is happening I will close it.
