### ISSUE TITLE
Don't disable buttons after applying hosts

### ISSUE THREAD

**Issue by FrankHB** [huhamhire/huhamhire-hosts#33]
This is a feature request.
After applying hosts, the "apply hosts" button and "save with ..." buttons would be disabled. This is a bit annoying. When testing the hosts file, e.g. manually renamed or cut it away, or if I want to save file elsewhere after applying, I have to click "download data file" to enable these buttons again.

**Comment by huhamhire** [comment]
You can just click the "Check update / Refresh" button. :-)

**Comment by FrankHB** [comment]
Got it.
