### ISSUE TITLE
Google is not available

### ISSUE THREAD

**Issue by johndeng** [huhamhire/huhamhire-hosts#37]
Hi, Huhamhire team. The Google host is not available, could you make a tiny update? It will very grateful.

**Comment by octopusthu** [comment]
Same here in Beijing. Access to Google sites became very slow since yesterday (2014.7.24).

**Comment by huhamhire** [comment]
data file has been updated to 1.4.9 :-)

**Comment by johndeng** [comment]
@huhamhire Awesome.

**Comment by octopusthu** [comment]
Excellent! It works again!!
