### ISSUE TITLE
Can not access twitter through chrome

### ISSUE THREAD

**Issue by nblintao** [huhamhire/huhamhire-hosts#41]
I can open `http://www.twitter.com/` on firefox, but not on chrome. (I have applied the latest hoottool) Why was that?

**Comment by nblintao** [comment]
原来twitter的真正地址是`https://twitter.com/`，加了www就不对了。firefox为什么能智能地跳过去，而chrome不行。
这个Issue可以close了。

**Comment by huhamhire** [comment]
twitter 一直比较诡异 :8ball:
