### ISSUE TITLE
bogus-nxdomain ip 220.250.64.20

### ISSUE THREAD

**Issue by iptux** [huhamhire/huhamhire-hosts#48]
IP 220.250.64.20 其实指向 nfdnserror3.wo.com.cn，是联通的 DNS 错误页面，[参考链接](https://github.com/felixonmars/dnsmasq-china-list/blob/master/bogus-nxdomain.china.conf#L14)

**Comment by PaleNeutron** [comment]
似乎是208.80.154.224？这个是google的dns解析的
——————
直接访问还是跪……也不是

**Comment by iptux** [comment]
in host version 1.5.1, this IP is resolved to the following domains:

```
aXXX.phobos.apple.com
l.yimg.com
dl-clientXXX.dropbox.com
dl-debugXX.dropbox.com
clientXX.dropbox.com
cplog.flashget.com
premium.nl.avira-update.com
www8.multiupload.com
www23.multiupload.com
```
