### ISSUE TITLE
可以追加android-developers.blogspot.com吗？

### ISSUE THREAD

**Issue by zbin** [huhamhire/huhamhire-hosts#52]
google 家的全被墙了，blogspot也访问不了了。每次都是自己ping然后改的。发现是某个子域名出现了问题 https://android-developers.blogspot.com/

**Comment by huhamhire** [comment]
因为 hosts 文件不支持泛域名解析，目前只增加单独的 blogspot 域名不能解决普遍性问题，暂时还不会对这类站点进行维护
