### ISSUE TITLE
建议增加ted.com的host

### ISSUE THREAD

**Issue by EdwardYuan** [huhamhire/huhamhire-hosts#54]
这两天发现ted也被墙掉了，能不能增加这个？

**Comment by zqhxuyuan** [comment]
同求slideshare

**Comment by samsong8610** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

openstack.org最近也不行了

On 11/06/2014 08:53 AM, zqh wrote:

> 同求slideshare
> 
> --- Reply to this email directly or view it on GitHub: 
> https://github.com/huhamhire/huhamhire-hosts/issues/54#issuecomment-61910350
> 
> -----BEGIN PGP SIGNATURE-----
> Version: GnuPG v2.0.14 (GNU/Linux)

iQEcBAEBAgAGBQJUWt1rAAoJEPDWvv0r0XeRK9MH/jZHaiUcSceU4XxJiT7oau0b
QScZJ0D/BbvgApqe9t1xGq1U4PPsMm2QP5UyQbNUtW9+suDDno8XrOws3/5EhHLL
yRsBGp5uO7K5Bo91JfCIxwzlUjoqaQUTvHbIsFuitAcaF1uD2FGytfZ2xGe6ZdTF
gZMuMysB3A8Af76WIie8ZiO7rZ9iCclCZPLbrEPfWI3rtGzLmSOrRXtIt3IOaKs8
6lBXadi7randg6o11U0Z0lXaF76+T4VZQoehExGflCuLFCH4959lFUe2zm59FgzR
nSrBCWLCwyTwSHd89QBaDSzWYX7bX+bsNgesqIdFU0lltCKMWLdHoML0OLcft0k=
=erS3
-----END PGP SIGNATURE-----
