### ISSUE TITLE
1.5.1 more issues report

### ISSUE THREAD

**Issue by ghost** [huhamhire/huhamhire-hosts#61]
1.  google ips seem no longer usable since the day before yesterday afaik.
2.  Hosts in android still have issues, for instance, connecting to google server.  Btw, loading a webpage is so slow.
3. Firefox add-ons still cannot open. If needed, I can provide a screenshot.
4. With your hosts, I cannot open Deviantart. Unless I delete your hosts. This is really odd..

Please fix. ;-)

**Comment by EdwardYuan** [comment]
+1  今天也发现google得服务用不了了 版本1.5.1 日期：2014-11-23

**Comment by ghost** [comment]
@EdwardYuan 1.5.2 has been released, let's test. ;- )

**Comment by ghost** [comment]
我的测试结果：
1. 在获取hosts的时候，只有西雅图服务器能用，相信其他服务器还没有同步好。
2. google的ip能够使用了，多谢！但是，用google搜索后，重定向到某些网站的时候，速度有些慢。
3. hosts的安卓版本我会等到cm-11-M12-xxx.zip出来后，测试。
4. 火狐的附加组件，问题依旧。我不知道与hosts是否相关，自从学联那事发生后，我这里就没好过。
    图片如下：

![firefox-addons](https://cloud.githubusercontent.com/assets/7656607/5388128/638bdcc0-8120-11e4-925b-a3e24661254e.png)
我能够打开add-ons manager，但是，深入点击，就会出现如上图那样的链接问题。解决办法倒是有：将secutiry.OCSP.enable的值从1（true）改成0(False)，然后刷新，就可以.但是这样做的结果是: Author not verified.我可不想用这样的办法，来更新附加组件。
5. devantart还是打不开，直接输入网址不行，google搜索devantart，然后重定向也打不开.

**Comment by EdwardYuan** [comment]
@rtlanceroad  Thanks. I've tried, it's ok to for google services now.

**Comment by EdwardYuan** [comment]
@rtlanceroad  我测试除了google code其他都正常，我这边以前也是这样。

**Comment by ghost** [comment]
@EdwardYuan google code和sourceforge是硬伤。我习惯将其描述成a big pain in the ass. 我能够打开code.google.com/p/xxx 和sourceforge.net/p/xxxx,但是，却不能解析xxx.googlecode.com和xxx.sourceforge.net....A big pain in the ass, indeed.

**Comment by huhamhire** [comment]
@rtlanceroad 因为 hosts 不支持泛域名解析，googlecode 和 SF 都使用了二级域名，同样还有 blogspot

**Comment by ghost** [comment]
@huhamhire  Indeed...

**Comment by EdwardYuan** [comment]
@rtlanceroad 嗯 这个确实很蛋疼……

**Comment by ghost** [comment]
版本已过时，我决定关闭这个bug.
