### ISSUE TITLE
Cannot search for data update

### ISSUE THREAD

**Issue by lychichem** [huhamhire/huhamhire-hosts#68]
As my title says, all the four server in the utility cannot refresh data. Every time when you click refresh the connection will abort. On Windows 7 x64 and tool 1.9.8 beta 5 x64.

**Comment by huhamhire** [comment]
I'm sorry that all of the automatic update methods are down currently, but you can still get the data file manually from sourceforge 
https://sourceforge.net/projects/huhamhirehosts/files/update/

**Comment by lychichem** [comment]
I've seen this file. Maybe the last method. Sigh...
